# for a list of excluded URLs see `.lycheeignore`

# suggested setting for non-interactive environments such as CIs
no_progress = true

# we use localhost links extensively in end-to-end tests
exclude_loopback = true

# enable cache since the check will be performed frequently
cache = true

# discard all cached requests older than this duration.
max_cache_age = "2d"

# only check 5 URLs at a time
max_concurrency = 5

# Ignore
# - relative links the lint website templates
# - links in the linkita git submodule
exclude_path = ["alpm-lint-website/templates", "alpm-lint-website/themes"]
