use std::path::PathBuf;
use std::string::FromUtf8Error;

use thiserror::Error;

/// The high-level error that can occur when using this crate.
///
/// Notably, it contains two important enums in the context of parsing:
/// - `ParseError` is a already formatted error generated by the `winnow` parser. This effectively
///   means that some invalid data has been encountered.
/// - `SourceInfoErrors` is a list of all logical or lint errors that're encountered in the final
///   step. This error also contains the original file on which the errors occurred.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum Error {
    /// ALPM type error
    #[error("ALPM type parse error: {0}")]
    AlpmType(#[from] alpm_types::Error),

    /// IO error
    #[error("I/O error while {0}:\n{1}")]
    Io(&'static str, std::io::Error),

    /// IO error with additional path info for more context.
    #[error("I/O error at path {0:?} while {1}:\n{2}")]
    IoPath(PathBuf, &'static str, std::io::Error),

    /// UTF-8 parse error when reading the input file.
    #[error(transparent)]
    InvalidUTF8(#[from] FromUtf8Error),

    /// No input file given
    #[error("No input file given.")]
    NoInputFile,

    /// A Parsing error that occurred during the winnow file parsing.
    #[error("File parsing error:\n{0}")]
    ParseError(String),
}

/// A helper struct to provide proper line based error/linting messages.
///
/// This is just a list of [`SourceInfoError`]s, in combination with the file's content on which the
/// errors where thrown. It implements several functions for error handling and error formatting.
#[derive(Debug)]
pub struct SourceInfoErrors {
    pub inner: Vec<SourceInfoError>,
    pub file_content: String,
}

/// This error describes some error variants that may appear when going through the parsed content
/// of a SRCINFO file.
///
/// This includes linting errors, deprecation warnings and hard unrecoverable errors.
#[derive(Debug)]
pub struct SourceInfoError {
    pub error_type: SourceInfoErrorType,
    pub line: Option<usize>,
    pub message: String,
}

#[derive(Debug)]
pub enum SourceInfoErrorType {
    Lint,
    Deprecation,
    Unrecoverable,
}

/// Create an unrecoverable SourceInfo error.
pub fn unrecoverable(line: Option<usize>, message: impl ToString) -> SourceInfoError {
    SourceInfoError {
        error_type: SourceInfoErrorType::Unrecoverable,
        line,
        message: message.to_string(),
    }
}

/// Create a SourceInfo linter error.
pub fn lint(line: Option<usize>, message: impl ToString) -> SourceInfoError {
    SourceInfoError {
        error_type: SourceInfoErrorType::Lint,
        line,
        message: message.to_string(),
    }
}

/// Create a SourceInfo deprecation warning.
pub fn deprecation(line: Option<usize>, message: impl ToString) -> SourceInfoError {
    SourceInfoError {
        error_type: SourceInfoErrorType::Deprecation,
        line,
        message: message.to_string(),
    }
}
