//! All error types that are exposed by this crate.
use std::{path::PathBuf, string::FromUtf8Error};

use alpm_pkgbuild::error::Error as PkgbuildError;
use thiserror::Error;

use crate::pkgbuild_bridge::error::BridgeError;
#[cfg(doc)]
use crate::{SourceInfoV1, source_info::parser::SourceInfoContent};

/// The high-level error that can occur when using this crate.
///
/// Notably, it contains an important enum in the context of parsing:
/// - `ParseError` is an already formatted error generated by the `winnow` parser. This effectively
///   means that some invalid data has been encountered
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum Error {
    /// ALPM type error
    #[error("ALPM type parse error: {0}")]
    AlpmType(#[from] alpm_types::Error),

    /// IO error
    #[error("I/O error while {0}:\n{1}")]
    Io(&'static str, std::io::Error),

    /// IO error with additional path info for more context.
    #[error("I/O error at path {0:?} while {1}:\n{2}")]
    IoPath(PathBuf, &'static str, std::io::Error),

    /// UTF-8 parse error when reading the input file.
    #[error(transparent)]
    InvalidUTF8(#[from] FromUtf8Error),

    /// A section or keyword is missing for a SRCINFO schema version.
    #[error("The SRCINFO data misses the required keyword '{keyword}'")]
    MissingKeyword {
        /// The missing keyword.
        keyword: &'static str,
    },

    /// No input file given.
    ///
    /// This error only occurs when running the [`crate::commands`] functions.
    #[error("No input file given.")]
    NoInputFile,

    /// A parsing error that occurred during winnow file parsing.
    #[error("File parsing error:\n{0}")]
    ParseError(String),

    /// JSON error while creating JSON formatted output.
    ///
    /// This error only occurs when running the [`crate::commands`] functions.
    #[error("JSON error: {0}")]
    Json(#[from] serde_json::Error),

    /// Unsupported schema version
    #[error("Unsupported schema version: {0}")]
    UnsupportedSchemaVersion(String),

    /// A alpm-pkgbuild bridge error that occurred when converting a PKGBUILD to a [`SourceInfoV1`]
    /// struct.
    ///
    /// See [`PkgbuildError`] for further details.
    #[error(transparent)]
    BridgeError(#[from] PkgbuildError),

    /// A logical error occurred when transforming `alpm-pkgbuild-bridge` script output to a
    /// [`SourceInfoV1`] struct.
    ///
    /// See [`BridgeError`] for further details.
    #[error(transparent)]
    BridgeConversionError(#[from] BridgeError),
}
