#![doc = include_str!("../README.md")]

/// Commandline argument handling. This is most likely not interesting for you.
pub mod cli;
/// Commandline argument handling. This is most likely not interesting for you.
pub mod commands;
/// All error types that're exposed by this crate.
pub mod error;
/// This is the final merged representation of a [`MergedPackage`] for a given
/// [`Architecture`](alpm_types::Architecture) and what you're probably looking for.
///
/// These are generated by calling
/// [`SourceInfo::packages_for_architecture`](source_info::SourceInfo::packages_for_architecture).
pub mod merged;
/// This module contains the first parsing pass a SRCINFO file.
/// It returns a rather raw line-based, but already typed representation of the file content.
/// This isn't yet useful for consumers and needs to be further processed.
pub mod parser;
/// This module contains the second parsing and linting pass.
/// The raw representation from the [`parser`] module is brought into a proper struct-based
/// representation that fully represents the SRCINFO file (except comments and empty lines).
///
/// The [`source_info::SourceInfo::from_parsed`] function also returns an error array instead of a
/// `Result` as those errors may only be linting errors that can be ignored.
/// The consumer has handle those errors and decide what to do do based on their type.
pub mod source_info;

// Expose the most important structs to the top of the library so that they can be easily
// discovered.
pub use error::Error;
pub use merged::MergedPackage;
pub use source_info::SourceInfo;
