#![doc = include_str!("../README.md")]

use std::{
    io::{self, IsTerminal, Read},
    path::PathBuf,
};

use error::SourceInfoErrors;

use crate::{error::Error, source_info::SourceInfo};

/// Commandline argument handling. This is most likely not interesting for you.
pub mod cli;
/// All error types that're exposed by this crate.
pub mod error;
/// This is the final merged representation of a [`MergedPackage`] for a given [`Architecture`] and
/// what you're probably looking for.
///
/// These are generated by calling
/// [`SourceInfo::packages_for_architecture`](source_info::SourceInfo::packages_for_architecture).
pub mod merged;
/// This module contains the first parsing pass a SRCINFO file.
/// It returns a rather raw line-based, but already typed representation of the file content.
/// This isn't yet useful for consumers and needs to be further processed.
pub mod parser;
/// This module contains the second parsing and linting pass.
/// The raw representation from the [`parser`] module is brought into a proper struct-based
/// representation that fully represents the SRCINFO file (except comments and empty lines).
///
/// The [`source_info::SourceInfo::from_parsed`] function also returns an error array instead of a
/// `Result` as those errors may only be linting errors that can be ignored.
/// The consumer has handle those errors and decide what to do do based on their type.
pub mod source_info;

/// A small wrapper around the parsing of a Srcinfo file that simply ensures that there were no
/// errors.
pub fn validate(file: Option<&PathBuf>) -> Result<(), Error> {
    parse(file)?;

    Ok(())
}

/// Parse and interpret a Srcinfo file.
///
/// NOTE: If a command is piped to this process, the input is read from stdin.
/// See [`IsTerminal`] for more information about how terminal detection works.
///
/// [`IsTerminal`]: https://doc.rust-lang.org/stable/std/io/trait.IsTerminal.html
///
/// # Errors
///
/// Returns an error if the input can not be parsed and validated, or if the output can not be
/// formatted in the selected output format.
///
/// Furthermore, returns an error array with potentially un/-recoverable (linting-)errors, this
/// needs to be explicitly handled by the user.
pub fn parse(file: Option<&PathBuf>) -> Result<(SourceInfo, Option<SourceInfoErrors>), Error> {
    if let Some(path) = file {
        // Read directly from file.
        SourceInfo::from_file(path)
    } else if !io::stdin().is_terminal() {
        // Read from stdin into string.
        let mut buffer = Vec::new();
        let mut stdin = io::stdin();
        stdin
            .read_to_end(&mut buffer)
            .map_err(|err| Error::Io("reading from stdin", err))?;
        let content = String::from_utf8(buffer)?.to_string();

        // Convert into SourceInfo
        SourceInfo::from_string(&content)
    } else {
        Err(Error::NoInputFile)
    }
}
