[package]
authors.workspace = true
description = "Python bindings for the ALPM project"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "python-alpm"
publish = false
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0-alpha.0"

[lib]
crate-type = ["cdylib"]
name = "python_alpm"

[dependencies]
alpm-common.workspace = true
alpm-srcinfo.workspace = true
alpm-types.workspace = true
pyo3 = { version = "0.26", features = ["abi3-py310", "extension-module"] }
semver.workspace = true
strum.workspace = true

[lints]
workspace = true
