[build-system]
build-backend = "maturin"
requires = ["maturin>=1.8,<2.0"]

[project]
classifiers = [
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Rust",
]
dynamic = ["version"]
license = "Apache-2.0 OR MIT"
name = "alpm"
requires-python = ">=3.10"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "alpm._native"
python-source = "python"

[dependency-groups]
dev = [
    "mypy>=1.17,<2.0",
    "pdoc>=15.0,<16.0",
    "pytest>=8.4,<9.0",
    "ruff>=0.13,<0.14",
]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = ["D", "E", "F", "I"]

# Ignore conflicting docstring rules (for google style)
ignore = ["D203", "D213"]

[tool.ruff.lint.per-file-ignores]
"python/**" = ["I"] # We need to manually order imports in stubs
"tests/**" = ["D"]

[tool.pytest.ini_options]
addopts = "--doctest-modules --doctest-continue-on-failure --doctest-glob README.md"
