[build-system]
build-backend = "maturin"
requires = ["maturin>=1.8,<2.0"]

[project]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Rust",
]
description = "Python bindings for the Rust-based ALPM project"
dynamic = ["version"]
keywords = ["alpm", "archlinux", "packaging", "srcinfo"]
license = "Apache-2.0 OR MIT"
name = "python-alpm"
readme = "README.md"
requires-python = ">=3.10"

[project.urls]
Changelog = "https://alpm.archlinux.page/python-alpm/CHANGELOG.html"
Documentation = "https://alpm.archlinux.page/pdoc/"
Homepage = "https://alpm.archlinux.page/python-alpm/"
Issues = "https://gitlab.archlinux.org/archlinux/alpm/alpm/-/issues"
Repository = "https://gitlab.archlinux.org/archlinux/alpm/alpm"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "alpm._native"
python-source = "python"

[dependency-groups]
dev = [
    "mypy>=1.17,<2.0",
    "pdoc>=16,<16.1",
    "pytest>=8.4,<9.0",
    "ruff>=0.14,<0.15",
]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = ["D", "E", "F", "I"]

# Ignore conflicting docstring rules (for google style)
ignore = ["D203", "D213"]

[tool.ruff.lint.per-file-ignores]
"python/**" = ["I"] # We need to manually order imports in stubs
"tests/**" = ["D"]

[tool.pytest.ini_options]
addopts = "--doctest-modules --doctest-continue-on-failure --doctest-glob README.md"
