[package]
name = "alpm-soname"
description = "Library and commandline toolkit for looking up SONAMEs in ALPM context"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
default-run = "alpm-soname"

[[bin]]
name = "alpm-soname"
path = "src/main.rs"
required-features = ["cli"]

[features]
cli = ["dep:clap", "dep:log"]
default = ["cli"]

[dependencies]
alpm-package.workspace = true
alpm-pkginfo.workspace = true
alpm-types.workspace = true
clap = { workspace = true, optional = true }
goblin = "0.9.3"
lddtree = "0.3.7"
log = { version = "0.4.27", optional = true }
simplelog = "0.12.2"
thiserror.workspace = true
walkdir = "2.5.0"

[dev-dependencies]
alpm-mtree.workspace = true
rstest.workspace = true
tempfile.workspace = true
testresult.workspace = true
