[package]
authors.workspace = true
description = "Types for Arch Linux Package Management"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license = "(Apache-2.0 OR MIT) AND LGPL-2.0-or-later"
name = "alpm-types"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.8.0"

[features]
_winnow-debug = ["winnow/debug"]
# Enable tests that ensure that alpm is compatible to existing Arch Linux tooling.
# This requires certain Arch Linux related binaries to be installed on the system.
compatibility_tests = []

[dependencies]
alpm-parsers.workspace = true
blake2 = "0.10.6"
fluent-i18n.workspace = true
digest = "0.10.7"
email_address = "0.2.4"
log.workspace = true
md-5 = "0.10.5"
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1 = "0.10.5"
sha2 = "0.10.7"
spdx = "0.12.0"
strum.workspace = true
thiserror.workspace = true
time = "0.3.22"
url = { version = "2.4.0", features = ["serde"] }
winnow.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true
rstest.workspace = true
simplelog.workspace = true
testresult.workspace = true

[package.metadata.cargo-machete]
ignored = ["md-5"]

[lints]
workspace = true
