[package]
authors.workspace = true
description = "Types for Arch Linux Package Management"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "alpm-types"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.11.2"
exclude = ["**/snapshots/**"]

[features]
# Enable tests that ensure that alpm is compatible to existing Arch Linux tooling.
# This requires certain Arch Linux related binaries to be installed on the system.
_compatibility_tests = []
# Enable winnow debugging
_winnow-debug = ["winnow/debug"]
default = ["serde"]
# Enable serde de/serialization for all types.
serde = [
    "dep:serde",
    "dep:serde_with",
    "email_address/serde_support",
    "url/serde",
]

[dependencies]
alpm-parsers.workspace = true
base64 = "0.23.0"
blake2 = "0.10.6"
crc = "3.4.0"
fluent-i18n.workspace = true
digest = "0.10.7"
email_address = { version = "0.2.4", default-features = false }
log.workspace = true
md-5 = "0.10.5"
semver.workspace = true
serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }
sha1 = "0.10.5"
sha2 = "0.10.7"
spdx = "0.13.0"
strum.workspace = true
thiserror.workspace = true
time = "0.3.47"
url = "2.4.0"
winnow.workspace = true

[dev-dependencies]
insta.workspace = true
proptest.workspace = true
rstest.workspace = true
simplelog.workspace = true
serde_json.workspace = true
testresult.workspace = true
which.workspace = true

[package.metadata.cargo-machete]
ignored = ["md-5"]

[lints]
workspace = true
