"""Tests that all items in alpm_types module can be imported."""


def test_imports() -> None:
    """Test that all items can be imported without errors."""
    from alpm.alpm_types import (  # noqa: F401
        ALPMError,
        Architecture,
        Blake2b512Checksum,
        BuildEnvironmentOption,
        BzrInfo,
        ElfArchitectureFormat,
        Epoch,
        FossilInfo,
        FullVersion,
        GitInfo,
        HgInfo,
        License,
        Md5Checksum,
        OpenPGPKeyId,
        OpenPGPv4Fingerprint,
        OptionalDependency,
        PackageOption,
        PackageRelation,
        PackageRelease,
        PackageVersion,
        RelativePath,
        SchemaVersion,
        Sha1Checksum,
        Sha224Checksum,
        Sha256Checksum,
        Sha384Checksum,
        Sha512Checksum,
        SkippableBlake2b512Checksum,
        SkippableMd5Checksum,
        SkippableSha1Checksum,
        SkippableSha224Checksum,
        SkippableSha256Checksum,
        SkippableSha384Checksum,
        SkippableSha512Checksum,
        SonameV1,
        SonameV1Type,
        Source,
        SourceUrl,
        SvnInfo,
        Url,
        Version,
        VersionComparison,
        VersionRequirement,
        makepkg_option_from_str,
        openpgp_identifier_from_str,
        relation_or_soname_from_str,
    )
