def test_imports():
    """Test that all items can be imported without errors."""

    from alpm.alpm_types import (  # noqa: F401
        ALPMError,
        Checksum,
        Blake2b512Checksum,
        Md5Checksum,
        Sha1Checksum,
        Sha224Checksum,
        Sha256Checksum,
        Sha384Checksum,
        Sha512Checksum,
        BuildEnvironmentOption,
        PackageOption,
        makepkg_option_from_str,
        License,
        OpenPGPKeyId,
        OpenPGPv4Fingerprint,
        openpgp_identifier_from_str,
        RelativePath,
        Architecture,
        Url,
        Epoch,
        PackageRelease,
        PackageVersion,
        SchemaVersion,
        OptionalDependency,
        PackageRelation,
        SonameV1,
        SonameV1Type,
        relation_or_soname_from_str,
        VersionComparison,
        VersionRequirement,
        ElfArchitectureFormat,
        FullVersion,
        Version,
    )
