//! Parsing of pkgbuild-bridge output.
//!
//! This module revolves about parsing and verifying the output generated by the pkgbuild-bridge.sh
//! script that's shipped with this project.
//!
//! The output of the script has a well-known structure and provides some guarantees that we'll use
//! to keep the parsers simple.
//!
//! Overall format specification:
//! 1. Variable declarations happen one-line per variable.
//! 1. If a variable is an array, the array's values are represented as space separated values,
//!    surrounded by double quotes `"`. Quotes inside these strings are escaped as such: `\"`.
//! 1. All variables declaration lines begin with `VAR`
//! 1. pkgbase variable declarations look as follows:
//!
//!    ```text
//!    VAR GLOBAL [ARRAY|STRING] $KEY $VALUES
//!    Examples:
//!    VAR GLOBAL STRING pkgrel "6"
//!    VAR GLOBAL ARRAY license "GPL-2.0-or-later" "CCPL"
//!    ```
//!
//! 1. pkgbase variable declarations look as follows:
//!
//!    ```txt
//!    VAR FUNCTION $PACKAGE_NAME [ARRAY|STRING] $KEY $VALUES
//!    Examples:
//!    VAR FUNCTION package_my-split-package STRING pkgdesc "My special split package"
//!    VAR FUNCTION package_my-split-package ARRAY depends "cargo" "glibc"
//!    ```
//! 1. Package overrides that clear a value/array simply don't have any string values.
//!
//!    Example: `VAR FUNCTION package_my-split-package ARRAY depends`
//! 1. Split-/Package functions are declared such: `FUNCTION $PACKAGE_NAME`
//!
//!    Example: `FUNCTION
//!    package_my-split-package` Note that single-package PKGBUILD files don't necessarily need to
//!    have the `package-$NAME` format, but rather may just have a single `package` function.
//!
//! Structure guarantees:
//! 1. There're no empty lines
//! 1. All pkgbase variables come first
//! 1. All package specific variables come next, clustered by package.
//! 1. All function declarations come at the end.

mod package_base;

use winnow::{
    ModalResult,
    Parser,
    ascii::{space0, space1},
    combinator::{alt, cut_err, eof, preceded, repeat, terminated},
    error::{StrContext, StrContextValue},
    token::{none_of, one_of},
};

pub enum Property {
    SingleValue(),
    ArrayValue(),
}

/// Recognizes a list of string value while handling the surroundings.
/// Each value is then directly `try_map`ped via the specified function.
///
/// Consumes leading and trailing spaces while also consuming newlines.
/// Also allows variables at the end of the file where no newline is found.
/// Calls [parse_next_string] for variable parsing.
fn value_list_till_newline<T, C, E>(input: &mut &str, mut try_map_fn: C) -> ModalResult<Vec<T>>
where
    C: FnMut(&str) -> Result<T, E>,
    E: Into<alpm_types::Error>,
{
    let values = repeat(
        0..,
        preceded(
            space1,
            cut_err(parse_next_value.try_map(|s| try_map_fn(&s).map_err(|err| err.into()))),
        ),
    )
    .parse_next(input)?;

    // Make sure we find the end of the line after the last element in the list.
    cut_err(preceded(space0, alt(("\n", eof))))
        .context(StrContext::Label("character"))
        .context(StrContext::Expected(StrContextValue::Description(
            "end of line or end of file.",
        )))
        .parse_next(input)?;

    Ok(values)
}

/// Recognizes a single string value while handling the surroundings.
/// The value is then directly `try_map`ped via the specified function.
///
/// Consumes leading and trailing spaces while also consuming newlines.
/// Also allows variables at the end of the file where no newline is found.
/// Calls [parse_next_string] for variable parsing.
fn value_till_newline<T, C>(input: &mut &str, mut try_map_fn: C) -> ModalResult<T>
where
    C: FnMut(&str) -> Result<T, alpm_types::Error>,
{
    preceded(
        space1,
        terminated(
            cut_err(parse_next_value.try_map(|s| try_map_fn(&s))),
            (space0, alt(("\n", eof))),
        ),
    )
    .parse_next(input)
}

/// Recognizes a single string value while handling the surroundings.
///
/// Consumes leading and trailing spaces while also consuming newlines.
/// Also allows variables at the end of the file where no newline is found.
/// Calls [parse_next_string] for variable parsing.
fn string_value_till_newline(input: &mut &str) -> ModalResult<String>
where
{
    preceded(
        space1,
        terminated(cut_err(parse_next_value), (space0, alt(("\n", eof)))),
    )
    .parse_next(input)
}

/// Recognizes a list of string value while handling the surroundings.
///
/// Consumes leading and trailing spaces while also consuming newlines.
/// Also allows variables at the end of the file where no newline is found.
/// Calls [parse_next_string] for variable parsing.
fn string_value_list_till_newline(input: &mut &str) -> ModalResult<Vec<String>>
where
{
    let values = repeat(0.., preceded(space1, cut_err(parse_next_value))).parse_next(input)?;

    // Make sure we find the end of the line after the last element in the list.
    cut_err(preceded(space0, alt(("\n", eof))))
        .context(StrContext::Label("character"))
        .context(StrContext::Expected(StrContextValue::Description(
            "end of line or end of file.",
        )))
        .parse_next(input)?;

    Ok(values)
}

/// Recognizes a single string value.
///
/// Calls [variable_character] for escaped character handling.
///
/// Example:
/// `"This is a string value\" with escaped \\ characters"`
fn parse_next_value(input: &mut &str) -> ModalResult<String> {
    // We expect a value surrounded with double quotes (") that may contain escaped characters.
    // As we resolve the escaping, we cannot just `.take()`. Instead we have to accumulate in
    // a String.
    let string_value = preceded(
        '\"',
        cut_err(terminated(
            repeat(0.., variable_character).fold(String::new, |mut string, c| {
                string.push(c);
                string
            }),
            '\"',
        )),
    )
    .parse_next(input)?;

    Ok(string_value)
}

/// Recognizes a single character in a string variable.
/// This is necessary as characters might be escaped, such as `\"`.
///
/// Consumes as single character and returns afterwards.
/// Backtracks if a stand-alone `"` is encountered.
fn variable_character(input: &mut &str) -> ModalResult<char> {
    let c = none_of('\"').parse_next(input)?;
    if c == '\\' {
        one_of(['"', '\\'])
            .context(StrContext::Label("escaped sequence"))
            .context(StrContext::Expected(StrContextValue::Description(
                "one of the allowed escape characters: ['\"', '\\']",
            )))
            .parse_next(input)
    } else {
        Ok(c)
    }
}
