[package]
name = "uapi-verifier-directory"
description = "UAPI Signature Verifier Directory for distributions"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
log = "0.4"
